import os

DB_HOST = os.environ.get("CALINIFY_DATABASE_HOST")
DB_USERNAME = os.environ.get("CALINIFY_DATABASE_USERNAME")
DB_PASSWORD = os.environ.get("CALINIFY_DATABASE_PASSWORD")
DB_PORT = os.environ.get("CALINIFY_DATABASE_PORT")
DB_TABLE_NAME = os.environ.get("CALINIFY_DATABASE_TABLE_NAME")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

GPT_PLAIN_TEXT_MODEL = os.environ.get("GPT_PLAIN_TEXT_MODEL")