import os

from dotenv import dotenv_values

ENV = dotenv_values(f'{os.path.dirname(__file__)}/.env')

CALINIFY_DATABASE_HOST = ENV["CALINIFY_DATABASE_HOST"]
CALINIFY_DATABASE_USERNAME = ENV["CALINIFY_DATABASE_USERNAME"]
CALINIFY_DATABASE_PASSWORD = ENV["CALINIFY_DATABASE_PASSWORD"]
CALINIFY_DATABASE_PORT = ENV["CALINIFY_DATABASE_PORT"]
CALINIFY_DATABASE_TABLE_NAME = ENV["CALINIFY_DATABASE_TABLE_NAME"]

OPENAI_API_KEY = ENV["OPENAI_API_KEY"]

GPT_PLAIN_TEXT_MODEL = ENV["GPT_PLAIN_TEXT_MODEL"]